//
// Microsoft Enterprise SOC Lab
// Query: Account and Group Discovery Investigation
// Purpose: Identify local group membership enumeration activity.
// Event IDs:
//   4798 = A user's local group membership was enumerated
//   4799 = A security-enabled local group membership was enumerated
// Data Source: SecurityEvent
//

SecurityEvent
| where TimeGenerated > ago(24h)
| where Computer =~ "LAPTOP-JM2CHLK8"
| where EventID in (4798, 4799)
| project TimeGenerated, Computer, EventID, Activity, Account, SubjectAccount
| order by TimeGenerated desc
| take 50
