//
// Microsoft Enterprise SOC Lab
// Query: Windows Process Creation Investigation
// Purpose: Investigate processes created on the monitored endpoint.
// Event ID:
//   4688 = A new process has been created
// Data Source: SecurityEvent
//

SecurityEvent
| where TimeGenerated > ago(24h)
| where Computer =~ "LAPTOP-JM2CHLK8"
| where EventID == 4688
| project TimeGenerated, Computer, Account, NewProcessName, ParentProcessName, CommandLine
| order by TimeGenerated desc
| take 50
